/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_dynamodb_all_tables_region": "eu-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Campaigns-dev",
            "region": "eu-west-2"
        },
        {
            "tableName": "Users-dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "WorldFundAPI",
            "endpoint": "https://n2uas3gf72.execute-api.eu-west-2.amazonaws.com/dev",
            "region": "eu-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-2:1f8b9def-38ea-4f95-929b-2753a0090225",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_VraOhXL7i",
    "aws_user_pools_web_client_id": "1v1spsr1hon2m1atqrop262mt2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
